### ISSUE TITLE
"Page not found" for a brief moment before showing the right content after login

### ISSUE THREAD

**Issue by marciofrayze** [kraklin/elm-land-lamdera-auth-tailwind-template#2]
First of all, your project is awesome, thank you so much for sharing your knowledge!

I was able to run it locally and it works, but I get a white screen with a "Page not found" on the top left for a brief moment after login, and then the dashboard loads just fine.

Not sure if I'm doing something wrong or what.

**Steps to reproduce:**

- create a project based on this template
- add the `googleAppClientId` and `googleAppClientSecret` that you get from the Google Console into `Env.elm`
- in the Google Console, add `http://localhost:8000/login/OAuthGoogle/callback` as the redirect URL (is this correct? I hope so!)
- `npm install`
- `npm start`
- go to `http://localhost:8000` and log in
- keep watching the top left of the screen, the **"Page not found"** text appears just for a moment, and then it shows the dashboard.

**Expected behavior:**

Show a loading state while the backend is processing the request.

I think it takes a while for the `callbackForGoogleAuth` (from `Frontend.elm`) to finish processing, and in that time, the application is in an inconsistent state, resulting in a "Page not found" error.

**Comment by kraklin** [comment]
Hey @marciofrayze 

Thanks for checking this out. I think that it is caused by the fact that the route `/login/OAuthGoogle/callback` is being picked up by elm-land and it thinks it does not exists.

I think that adding a `Login/ALL_.elm` would help with not showing Page not found even though it would be better to circumvent the routing for certain routes completely.

Feel free to dig into it and push PR with the solution. I might not have much time at my hand to solve this now.

**Comment by kraklin** [comment]
Ok, I tried it out and it works, so I have added this to the template - now you have a catch all /login/* route for callbacks that you can either style or let it be as it is being shown for a brief moment.

It is not the best solution for this, but I am afraid that if we would like to use elm-land, we need to accept this workaround.

Would you consider this a fix for this issue @marciofrayze ?

**Comment by marciofrayze** [comment]
Thank you @kraklin, just tested it out, and the issue is fixed! 🌈🌲
